name: Run Python Scripts on Push

on:
  push:
    branches: [ "main" ]

jobs:
  run-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || echo "No requirements.txt found"

    - name: Run config validation script
      run: |
        python scripts/validate_config.py
